# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

steps:
  - task: DotNetCoreCLI@2
    inputs:
      azureSubscription: 'Azure subscription 1(b191d4ec-12f0-46bc-a78f-cbce8e9ad886)'
      command: 'build'
      workingDirectory: 'my-first-static-web-app-main'

pool:
  vmImage: ubuntu-latest